### ISSUE TITLE
[BUG]代码提示不工作，当命名空间中没有任何类型，只有其他命名空间时

### ISSUE THREAD

**Issue by ps5mh** [tangzx/EmmyLua-Unity#1]
代码提示不工作，当命名空间中没有任何类型，只有其他命名空间时

我在finish的时候自己写代码加了无效的类型到命名空间中，就可以提示了：
![image](https://user-images.githubusercontent.com/6095403/196610634-05b5c5e2-a61d-40ca-8595-6a83f1920de4.png)
看起来不是此插件的问题，而是emmylua的问题。

**Comment by CppCXY** [comment]
但是你提问错了地方，vscode emmylua-unity是另一个仓库

**Comment by ps5mh** [comment]
呃，明白了明白了
